CardGame_v2/CardGame_v2.Web/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using CardGame_v2.Web.Models;
using CardGame_v2.DAL.EDM;
using CardGame_v2.DAL.Logic;

namespace CardGame_v2.Web.Controllers
{
    public class AuthController : Controller
    {
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(UserLogin user)
        {
            bool hasAccess = AuthManager.AuthUser(user.Email, user.Password);

            user.Role = UserManager.GetRoleByEmail(user.Email);

            //Hier findet die Überprüfung statt
            //...
            //Überprüfung Ende
            if (hasAccess)
            {
                var authTicket = new FormsAuthenticationTicket(
                    1,                              //Ticketversion
                    user.Email,                     //Useridentifizierung
                    DateTime.Now,                   //Zeitpunkt der Erstellung
                    DateTime.Now.AddMinutes(20),    //Gültigkeitsdauer
                    true,                           //Persistentes Ticket ueber Sessions hinweg
                    user.Role                       //Userrolle(n)
                    );

                string encryptedTicket = FormsAuthentication.Encrypt(authTicket);

                var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);

                System.Web.HttpContext.Current.Response.Cookies.Add(authCookie);

                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Error", "Error");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Register(User regUser)
        {
            var dbUser = new tblUser();

            dbUser.firstname = regUser.FirstName;
            dbUser.lastname = regUser.LastName;
            
            dbUser.userpassword = regUser.Password;
            dbUser.email = regUser.Email;

            dbUser.username = ""; //Im Moment nicht in Verwendung
            dbUser.currency = 1000; //Jeder faengt mit 1000 Waehrung an

            dbUser.fkUserRole = 2; //Jeder ist per Default ein Spieler

            if (AuthManager.Register(dbUser))
            {
                int userID = UserManager.GetUserByEmail(dbUser.email).idUser;
                if (DeckManager.AddDefaultDecksByUserId(userID))
                    return RedirectToAction("Login");
            }
            return RedirectToAction("Error", "Error");
        }
    }
}

CardGame_v2/CardGame_v2.Web/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CardGame_v2.Web.Models;
using CardGame_v2.DAL.EDM;
using CardGame_v2.DAL.Logic;

namespace CardGame_v2.Web.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        [HttpGet]
        [Authorize(Roles = "player,admin")]
        public ActionResult Index()
        {
            UserProfile profile = new UserProfile();

            var dbUser = UserManager.GetUserByEmail(User.Identity.Name);

            profile.Currency = dbUser.currency;
            profile.Email = dbUser.email;
            profile.FirstName = dbUser.firstname;
            profile.LastName = dbUser.lastname;

            profile.NumDistinctCardsOwned = UserManager.GetNumDistinctCardsOwnedByEmail(User.Identity.Name);
            profile.NumDecksOwned = UserManager.GetNumDecksOwnedByEmail(User.Identity.Name);

            profile.NumTotalCardsOwned = UserManager.GetNumTotalCardsOwnedByEmail(User.Identity.Name);

            return View(profile);
        }

        [HttpGet]
        [Authorize(Roles = "player,admin")]
        public ActionResult CardCollection()
        {
            var cardCollection = new List<Card>();

            var dbCardList = UserManager.GetAllCardsByEmail(User.Identity.Name);

            foreach (var cc in dbCardList)
            {
                Card card = new Card();
                card.CardID = cc.idCard;
                card.Attack = cc.attack;
                card.CardName = cc.cardname;
                card.Life = cc.life;
                card.Mana = cc.manacost;
                card.Type = UserManager.CardTypeNames[cc.fkCardType ?? 0];

                cardCollection.Add(card);
            }

            return View(cardCollection);
        }

        [HttpGet]
        [Authorize(Roles = "player,admin")]
        public ActionResult DeckOverview()
        {
            var decks = new List<Deck>();

            var dbDecks = UserManager.GetAllDecksByEmail(User.Identity.Name);

            foreach(var d in dbDecks)
            {
                Deck deck = new Deck();
                deck.DeckID = d.idDeck;
                deck.Name = d.deckname;
                decks.Add(deck);
            }

            return View(decks);
        }

        [HttpGet]
        [Authorize(Roles = "player,admin")]
        public ActionResult DeckDetails(int id)
        {
            var deckCards = new List<Card>();

            var dbDeckCards = DeckManager.GetDeckCardsById(id);

            foreach (var cc in dbDeckCards)
            {
                Card card = new Card();
                card.CardID = cc.idCard;
                card.Attack = cc.attack;
                card.CardName = cc.cardname;
                card.Life = cc.life;
                card.Mana = cc.manacost;
                card.Type = UserManager.CardTypeNames[cc.fkCardType ?? 0];

                deckCards.Add(card);
            }

            return View(deckCards);
        }
    }
}

CardGame_v2/CardGame_v2.Web/Views/Shared/_CardList.cshtml
@model IEnumerable<Card>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(c => c.CardName)
        </th>
        <th>
            @Html.DisplayNameFor(c => c.Type)
        </th>
        <th>
            @Html.DisplayNameFor(c => c.Mana)
        </th>
        <th>
            @Html.DisplayNameFor(c => c.Attack)
        </th>
        <th>
            @Html.DisplayNameFor(c => c.Life)
        </th>
    </tr>

    @foreach (var card in Model)
    {
        <tr>
            <th>
                @Html.DisplayFor(c => card.CardName)
            </th>
            <th>
                @Html.DisplayFor(c => card.Type)
            </th>
            <th>
                @Html.DisplayFor(c => card.Mana)
            </th>
            <th>
                @Html.DisplayFor(c => card.Attack)
            </th>
            <th>
                @Html.DisplayFor(c => card.Life)
            </th>
        </tr>
    }

</table>

CardGame_v2/CardGame_v2.Web/Views/Shared/_DBCardList.cshtml
@model IEnumerable<Card>

<table class="table table-fixed">
    <thead>
        <tr>
            <th class="col-xs-6">@Html.DisplayNameFor(c => c.CardName)</th>
            <th class="col-xs-2">@Html.DisplayNameFor(c => c.Type)</th>
            <th class="col-xs-1">@Html.DisplayNameFor(c => c.Mana)</th>
            <th class="col-xs-1">@Html.DisplayNameFor(c => c.Attack)</th>
            <th class="col-xs-1">@Html.DisplayNameFor(c => c.Life)</th>
            <th class="col-xs-1"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var card in Model)
        {
            <tr>
                <td class="col-xs-6">@Html.DisplayFor(c => card.CardName)</td>
                <td class="col-xs-2">@Html.DisplayFor(c => card.Type)</td>
                <td class="col-xs-1">@Html.DisplayFor(c => card.Mana)</td>
                <td class="col-xs-1">@Html.DisplayFor(c => card.Attack)</td>
                <td class="col-xs-1">@Html.DisplayFor(c => card.Life)</td>
                <td class="col-xs-1">o</td>
            </tr>
        }
    </tbody>
</table>

CardGame_v2/CardGame_v2.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cardgame Shop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cardgame", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                        //if (User.IsInRole("role"))
                        //if (User.Identity.IsAuthenticated())
                        if (User.Identity.Name == "")
                        {
                            <li>@Html.ActionLink("Login", "Login", "Auth")</li>
                            <li>@Html.ActionLink("Register", "Register", "Auth")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Logout", "Logout", "Auth")</li>
                            <li>@Html.ActionLink(User.Identity.Name, "Index", "Profile")</li>
                            <li>@Html.ActionLink("Shop", "Index", "Shop")</li>
                            @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MAP Cardgame Shop</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>