CardGame/CardGame.Web/Models/Card.cs
using CardGame.Resources;
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace CardGame.Web.Models
{
    public class Card :IComparable<Card>
    {
        #region ID
        [Required]
        [HiddenInput(DisplayValue = false)]
        public int ID { get; set; } 
        #endregion

        #region NAME
        [Required(ErrorMessageResourceType = typeof(ValidationMessages),
ErrorMessageResourceName = Constants.Validation.PRODUCT_NAME)]
        [Display(Name = Constants.Labels.CARD_NAME, ResourceType = typeof(ValidationLabels))]
        public string Name { get; set; }
        #endregion

        #region MANA
        [Required(ErrorMessageResourceType = typeof(ValidationMessages),
ErrorMessageResourceName = Constants.Validation.NUMBER)]
        [Range(0, 50)]
        [Display(Name = Constants.Labels.MANA_COST, ResourceType = typeof(ValidationLabels))]
        public byte Mana { get; set; }
        #endregion

        #region ATTACK
        [Required(ErrorMessageResourceType = typeof(ValidationMessages),
ErrorMessageResourceName = Constants.Validation.NUMBER)]
        [Range(0, 50)]
        [Display(Name = Constants.Labels.ATTACK, ResourceType = typeof(ValidationLabels))]
        public short Attack { get; set; }
        #endregion

        #region LIFE
        [Required(ErrorMessageResourceType = typeof(ValidationMessages),
ErrorMessageResourceName = Constants.Validation.NUMBER)]
        [Range(0, 50)]
        [Display(Name = Constants.Labels.LIFE, ResourceType = typeof(ValidationLabels))]
        public short Life { get; set; }
        #endregion

        #region FLAVOR
        [Required(ErrorMessageResourceType = typeof(ValidationMessages),
ErrorMessageResourceName = Constants.Validation.DESCRIPTION)]
        [Display(Name = Constants.Labels.TEXT, ResourceType = typeof(ValidationLabels))]
        public string Flavor { get; set; }
        #endregion

        #region TYPE
        [Display(Name = Constants.Labels.TYPE, ResourceType = typeof(ValidationLabels))]
        public string Type { get; set; }

        #endregion

        
        #region ISACTIVE

        [Display(Name = Constants.Labels.ISACTIVE)]
        public bool IsActive
        { get; set;}
    #endregion

        #region IMAGE MIME TYPE
        public string ImageMimeType { get; set; }
        #endregion

        #region PIC
        public byte[] Pic { get; set; }
        #endregion



        #region COMPARE CARDS
        public int CompareTo(Card other)
        {
            if (this.ID == other.ID)
                return 0;
            else if (this.ID < other.ID)
                return -1;
            else //this.CardID > other.CardID
                return 1;
        }
        #endregion

        #region SORTVALUE
        [HiddenInput(DisplayValue = false)]
        public int? SortValue { get; set; }

        public int OwnerId { get; set; } 
        #endregion
    }
}

CardGame/CardGame.Web/Controllers/AdminController.cs
using System.Web.Mvc;
using CardGame.DAL.Logic;
using CardGame.Web.Models;
using System.Collections.Generic;
using log4net;
using System;
using System.Diagnostics;
using System.Web;
using CardGame.Web.Controllers.HtmlHelpers;
using CardGame.Web.Models.DB;
using CardGame.Web.Models.UI;

namespace CardGame.Web.Controllers
{
    public class AdminController : Controller
    {
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        HomeController a = new HomeController();

        #region ACTIONRESULT INDEX
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Index(int? sortValue, string search)
        {
            log.Info("AdminController-Index");

            try
            {
                List<CardPack> Cardpacks = new List<CardPack>();
                var dbpacks = PackManager.AdminGetAllPacks();
                foreach (var pack in dbpacks)
                {
                    CardPack p = new CardPack();
                    p.IdPack = pack.ID;
                    p.IsActive = pack.IsActive ?? true;
                    p.IsMoney = pack.IsMoney ?? false;
                    p.NumCards = pack.NumberOfCards ?? 0;
                    p.PackName = pack.Name?? "n/a";
                    p.PackPrice = pack.Price ?? 0;
                    p.Worth = pack.Worth ?? 0;
                    p.Flavor = pack.FlavorText ?? "n/a";

                    Cardpacks.Add(p);
                }
                var sorted = Cardpacks;
                if (sortValue != null)
                {
                    sorted = SortHelper.FilterCardPacks(Cardpacks, (int)sortValue);
                }
                if (search != null)
                {
                    sorted = SortHelper.FilterCardPacks(Cardpacks,search);
                }
                return View(sorted);
            }
            catch (Exception e)
            {
                Debugger.Break();
                log.Error("AdminController-Edit", e);
                return View("Error");
            }

        }
        #endregion

        #region ACTIONRESULT A_USER INDEX
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult A_UserIndex(int? sortValue, string search)
        {
            log.Info("AdminController-Index");

            try
            {
                List<AdminUserInfo> Users = new List<AdminUserInfo>();
                var dbuser = UserManager.GetAllUser();
                foreach (var user in dbuser)
                {
                    AdminUserInfo u = new AdminUserInfo();
                    u.ID = user.ID;
                    u.IsActive = user.IsActive ?? true;
                    u.IsDeleted = user.IsDeleted ?? false;
                    u.Firstname = user.FirstName ?? "n/a";
                    u.Lastname = user.LastName ?? "n/a";
                    u.Gamertag = user.GamerTag ?? "n/a";
                    u.Email = user.Email ?? "n/a";
                    u.CurrencyBalance = user.AmountMoney ?? 0;
                    u.userrole = user.UserRole ?? "n/a";
                    u.Pic = user.Avatar ;
                    u.ImageMimeType = user.AvatarMimeType ?? "n/a";
                    u.BanDate = user.BanDate ?? DateTime.MinValue;
                    u.EntryDate = user.EntryDate ?? DateTime.MinValue;
                    Users.Add(u);
                }
                var sorted = Users;
                if (sortValue != null)
                {
                    sorted = SortHelper.FilterUsers(Users, (int)sortValue);
                }
                if (search != null)
                {
                    sorted = SortHelper.FilterUsers(Users, search);
                }
                return View(sorted);
            }
            catch (Exception e)
            {
                Debugger.Break();
                log.Error("AdminController-A_UserIndex", e);
                return View("Error");
            }

        }
        #endregion

        #region ACTIONRESULT CARD INDEX
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult CardIndex(int? sortValue,string search)
        {
            log.Info("AdminController-CardIndex");

            try
            {
                List<Card> Cards = new List<Card>();
                var dbcards = CardManager.GetAllCards();
                foreach (var card in dbcards)
                {
                    Card c = new Card();
                    c.ID = card.ID;
                    c.IsActive = card.IsActive ?? true;
                    c.Mana = card.ManaCost;
                    c.Attack = card.Attack;
                    c.Name = card.Name ?? "n/a";
                    c.Life = card.Life;
                    c.Flavor = card.FlavorText ?? "n/a";
                    c.Type = CardManager.GetCardTypeById(card.ID_CardType);
                    c.Pic = card.Image;
                    c.ImageMimeType = card.ImageMimeType?? "n/a";

                    Cards.Add(c);
                }
                    var sorted = Cards;
                if (sortValue != null )
                {
                    sorted= SortHelper.FilterCards(Cards,(int)sortValue);
                }
                if (search!=null )
                {
                    sorted = SortHelper.FilterCards(Cards, search);
                }
                
                return View(sorted);
            }
            catch (Exception e)
            {
                Debugger.Break();
                log.Error("AdminController-CardIndex", e);
                return View("Error");
            }

        }
        #endregion

        #region ACTIONRESULT ORDER INDEX
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult OrderIndex(int? sortValue, string search)
        {
            log.Info("AdminController-OrderIndex");

            try
            {
                List<OrderInfo> Orders = new List<OrderInfo>();
                var dborder = ShopManager.AdminGetAllOrders();
                UserInfo user = new UserInfo();
                foreach (var order in dborder)
                {
                    OrderInfo o = new OrderInfo();
                    o.ID = order.ID;
                    o.isActive = order.IsActive ?? true;
                    o.TotalCost = order.TotalCost ?? 0;
                    o.NumberOfPackages = order.NumberOfPackagesBought??0;
                    o.Date = order.OrderDateTime ?? DateTime.MinValue;
                    o.CreditCard = order.KindOfPayment ?? "n/a";
                    user.Email = order.User.Email ?? "n/a";
                    user.Firstname = order.User.FirstName ?? "n/a";
                    user.Gamertag = order.User.GamerTag ?? "n/a";
                    user.Lastname = order.User.LastName ?? "n/a";
                    o.User = user;
                    Orders.Add(o);
                }
                var sorted = Orders;
                if (sortValue != null)
                {
                    sorted = SortHelper.FilterOrders(Orders, (int)sortValue);
                }
                if (search != null)
                {
                    sorted = SortHelper.FilterOrders(Orders, search);
                }
                return View(sorted);
            }
            catch (Exception e)
            {
                Debugger.Break();
                log.Error("AdminController-OrderIndex", e);
                return View("Error");
            }

        }
        #endregion

        #region ACTIONRESULT DISCOUNTINDEX
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult DiscountIndex(int? sortValue, string search)
        {
            log.Info("AdminController-DiscountIndex");

            try
            {
                List<Web.Models.Discount> Discountpacks = new List<Web.Models.Discount>();
                var dbdiscounts = PackManager.GetAlltDiscounts();
                foreach (var d in dbdiscounts)
                {
                    Web.Models.Discount disc = new Web.Models.Discount();
                    disc.ID = d.ID;
                    disc.EndDate = d.EndDate ?? DateTime.MinValue;
                    disc.StartDate = d.StartDate ?? DateTime.MinValue;
                    disc.DiscountAmount = d.Discount ?? 0;
                    CardPack p = new CardPack();
                    p.PackName = d.Pack.Name;
                    p.PackPrice = (int)d.Pack.Price;
                    p.Pic = d.Pack.Image;
                    p.IdPack = d.Pack.ID;
                    p.IsActive = d.Pack.IsActive ?? false;
                    p.PackPrice = d.Pack.Price ?? 0;
                    p.IsMoney = d.Pack.IsMoney ?? false;

                    disc.DiscountPack = p;
                    Discountpacks.Add(disc);
                    
                }
                var sorted = Discountpacks;
                //if (sortValue != null)
                //{
                //    sorted = SortHelper.FilterCardPacks(Discountpacks, (int)sortValue);
                //}
                //if (search != null)
                //{
                //    sorted = SortHelper.FilterCardPacks(Discountpacks, search);
                //}
                return View(sorted);
            }
            catch (Exception e)
            {
                Debugger.Break();
                log.Error("AdminController-DiscountIndex", e);
                return View("Error");
            }

        }
        #endregion

        #region VIEWRESULT A_USER EDIT
        /// <summary>
        /// Takes the UserId, gets the User
        /// from DB,returns a ViewResult with user
        /// </summary>

CardGame/CardGame.Web/Controllers/CardController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using CardGame.Web.Models;
using CardGame.DAL.Logic;
using System.Linq;
using log4net;
using CardGame.Web.Controllers.HtmlHelpers;

namespace CardGame.Web.Controllers
{
    public class CardController : Controller
    {
        HomeController a = new HomeController();

        public int Pagesize = 100;
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        #region ACTIONRESULT OVERVIEW
        /// <summary>
        /// takes  und die page
        /// Orders the card by id and
        /// gives all the cards back as a 
        /// model-ActionResult
        /// </summary>
        /// <param name="cardclass"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Overview(int? sortValue , string search,int page = 1)
        {
            log.Info("CardController-Overview");
            List<Web.Models.Card> CardList = new List<Web.Models.Card>();
            var dbCardlist = CardManager.GetAllCards();
            
            foreach (var c in dbCardlist)
            {
                log.Info("Deckcontroller-Editdeck");
                Web.Models.Card card = new Web.Models.Card();
                card.ID = c.ID;
                card.Name = c.Name;
                card.Mana = c.ManaCost;
                card.Attack = c.Attack;
                card.Life = c.Life;
                card.Pic = c.Image;
                card.Flavor = c.FlavorText;
                card.IsActive = c.IsActive ?? true ;
                card.Type = CardManager.GetCardTypeById(c.ID_CardType);
                CardList.Add(card);
            }

            if (sortValue!=null)
            {
                CardList = SortHelper.FilterCards(CardList, (int)sortValue);
            }
            if (search != null)
            {
                CardList = SortHelper.FilterCards(CardList, search);
            }


            CardsListViewModel model = new CardsListViewModel()
            {
                Cards = CardList/*.OrderBy(c => c.ID)*/
            //.Where(p => p.Type != null )
                           .Skip((page - 1) * Pagesize)
                           .Take(Pagesize),
                PagingInfo = new PageInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = Pagesize,
                    TotalItems = CardList.Count()
                }
            };
            return View(model);
        }
        #endregion

        #region ActionResult DETAILS
        /// <summary>
        /// Takes the id of a card and returns 
        /// the card 
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View</returns>
        public ActionResult Details(int id)
        {
            log.Info("CardController-Details");
            DAL.Model.Card dbcard = null;

            dbcard = CardManager.GetCardById(id);

            Web.Models.Card card = new Web.Models.Card();
            card.ID = dbcard.ID;
            card.Name = dbcard.Name;
            card.Mana = dbcard.ManaCost;
            card.Attack = dbcard.Attack;
            card.Life = dbcard.Life;
            card.Pic = dbcard.Image;
            card.Flavor = dbcard.FlavorText;
            card.Type = CardManager.GetCardTypeById(dbcard.ID_CardType);
            return View(card);
        } 
        #endregion
    }
}

CardGame/CardGame.Web/Views/Shared/_BannerAd.cshtml
@{
    ViewBag.Title = "_BannerAd";
}

<div class="banner"style="background-color:rgba(189, 102, 49, 0.30);box-shadow: 2px -5px 35px 16px rgba(125,108,73,0.33);border-width:0 0 0.50em;
	border-radius:1.0em;">
    <div class="w3-content w3-section">
        <img class="mySlides w3-animate-fading" src="~/Content/images/Banner/banner1.jpg" >
        <div class="mySlides w3-animate-fading bannertext"><br /><a href="@Url.Action("DisableCurrency", "CardPack")"><h3>Kauf dir neue Karten</h3></a></div>
        <img class="mySlides w3-animate-fading" src="~/Content/images/Banner/banner2.jpg">
        <div class="mySlides w3-animate-fading bannertext"><br /><a href="@Url.Action("DiscountOverview", "CardPack")"><h3>Jetzt Packs in Aktion:</h3></a></div>
       <img class="mySlides w3-animate-fading" src="~/Content/images/Cardpacks/4.png" style="max-width:5em;margin-left:10em" />
        <img class="mySlides w3-animate-fading" src="~/Content/images/Cardpacks/2.png" style="max-width:5em;margin-left:10em" />
        <img class="mySlides w3-animate-fading" src="~/Content/images/Cardpacks/1.png" style="max-width:5em;margin-left:10em" />
        <img class="mySlides w3-animate-fading" src="~/Content/images/Banner/banner3.jpg">
        <div class="mySlides w3-animate-fading bannertext"><br /><h3><a href="@Url.Action("Deckoverview", "Profile")">Bestücke deine Decks</a></h3></div>
        <img class="mySlides w3-animate-fading" src="~/Content/images/Banner/banner4.png">
    </div>
</div>

CardGame/CardGame.Web/Views/Shared/_CardList.cshtml
@using CardGame.Web.Models

@model IEnumerable<Card>
@{
    ViewBag.Title = "_CardList";
}



    <div class="col col-md-6 cardcol"">
        <div class="card-deck-wrapper col-md-12 cardcol" id="ShowNewCards">
            <div class="card-deck cardcol "style="max-height:-10em;">
                <h3>Deine Karten</h3>
                @foreach (var card in Model)
            {
                    <div class="card col-md-3">
                        @if (card.Pic != null)
                        {
                            var base64 = Convert.ToBase64String(card.Pic);
                            var imgSrc = String.Format("data:image/png;base64,{0}", base64);
                            <img class="cardpic" src="@imgSrc" />
                        }
                        else
                        {
                            <div class="card-header ">@Html.DisplayText("no Picture found")</div>
                        }
                        <div class="card-title ">
                            <h3 class="cardtitle">@Html.DisplayFor(c => card.Name)</h3>
                        </div>
                        <div class="card-footer ">
                            <h5>@Html.DisplayFor(c => card.Flavor)</h5>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

CardGame/CardGame.Web/Views/Shared/_Layout.cshtml
    
<!DOCTYPE html>
<html>
<!-- HEAD -->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CloneShop</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jqueryui")
    @Scripts.Render("~/bundles/modernizr")
    
    <meta name="Webshop" content="Webshop to buy CloneStone Cards" />
    <meta name="description" content="A Webshop to buy Clonestone Cards" />
</head>


<body>

    <div class="container maincontainer">
        <div class="row">
            <!-- PARTIAL VIEW -->
            @RenderBody()

        </div>

        <header>
            <div class="overlay"></div>
            <!-- NAVIGATION DEFAULT -->
            <nav class="navbar navbar-default navbar-fixed-bottom">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="~/Content/images/CS_Logo.png" /></a>
                        
                    </div>

                    <!-- NAVIGATION Collapse -->
                    <div class="collapse navbar-collapse dropup" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            @*-------------------------------------------------PLAYER--------------------------------------- ------*@
                            @if (User.IsInRole("player") || User.IsInRole("admin"))
                            {
                                //--HOME BUTTON   PLAYER--
                                <li>
                                    <a href="@Url.Action("Index", "Home")">Home</a>
                                </li>
                                //--SERVICES BUTTON PLAYER--
                                <li>
                                    <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        Services
                                    </a>
                                    <ul class="dropdown-menu dropup">
                                        <li><a href="@Url.Action("About", "Home")">Über uns</a></li>
                                        <li><a href="@Url.Action("Contact", "Home")">Kontakt</a></li>
                                    </ul>
                                </li>
                                //--MEIN Profil BUTTON PLAYER--
                                <li>
                                    <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        @{if (Session["Firstname"] != null)
                                            {
                                                    var firstname = (this.Session["Firstname"]) + "´s Profil"; @firstname

                                            }
                                        }
                                    </a>
                                    <ul class="dropdown-menu dropup">
                                        <li><a href = "@Url.Action("UProfile","Profile")">Deine Daten</a></li>
                                        <li><a href = "@Url.Action("Statistics", "Home")">Stats Webshop</a></li>
                                        <li><a href = "@Url.Action("CardCollection", "Profile")">Deine Karten</a></li>
                                        <li><a href = "@Url.Action("Deckoverview", "Profile")">Deine Decks</a></li>
                                    </ul>
                                </li>
                                            //--MEIN SHOP BUTTON PLAYER--
                                            <li>
                                                <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Shop
                                                </a>
                                                <ul class="dropdown-menu dropup">
                                                    <li><a href = "@Url.Action("EnableCurrency", "CardPack")">Guthaben aufladen</a></li>
                                                    <li><a href = "@Url.Action("DisableCurrency", "CardPack")">Karten kaufen</a></li>
                                                    <li><a href="@Url.Action("DiscountOverview", "CardPack")">Aktionen</a></li>
                                                </ul>
                                            </li>
                                            //--DECKS BUTTON PLAYER--
                                            <li>
                                                <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Decks
                                                </a>
                                                <ul class="dropdown-menu dropup">
                                                    <li><a href = "@Url.Action("Overview", "Card")">Kartenübersicht</a></li>
                                                    <li><a href = "@Url.Action("Deckoverview", "Profile")">Decks</a></li>
                                                </ul>
                                            </li>
                                            //--LOGOUT BUTTON PLAYER--
                                            <li>
                                                <a href = "@Url.Action("Logout", "Account")">Log Out</a>
                                              </li>
                                            //--NAVCOIN PLAYER--
                                            <li>
                                                <a class="navcointop" href="@Url.Action("EnableCurrency", "CardPack")">
                                                    <img class="navcointoppic" src="~/Content/images/Coins-PNG-Picture-180x180.png" />

                                                    @{if (Session["CurrencyBalance"] != null)
                                                        {
                                                            var currency = this.Session["CurrencyBalance"];
                                                    @currency
                                                        }
                                                    }
                                                </a>
                                            </li>
                                                        }
                                                        @*---------------------------------VISITOR----------------------------*@
                            else
                            {
                                <li><a href="@Url.Action("Login", "Account")">Login</a></li>


                                <li><a href="@Url.Action("Contact","Home")">Zu den AGB´s </a></li>


                                <li><a href="@Url.Action("Register", "Account")">Registrieren</a></li>
                            }

                            @*--------------------------------------ADMIN-------------------------------------*@
                            @if (User.IsInRole("admin"))
                            {

                                <li>
                                    <a class="dropdown-toggle dropup" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Adminzone <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="@Url.Action("Index","Admin")">Pakete-Übersicht</a></li>
                                        <li><a href="@Url.Action("CardIndex","Admin")">Karten-Übersicht</a></li>
                                        <li><a href="@Url.Action("OrderIndex","Admin")">Order-Übersicht</a></li>
                                        <li><a href="@Url.Action("A_UserIndex","Admin")">User-Übersicht</a></li>
                                        <li><a href="@Url.Action("DiscountIndex","Admin")">Aktions-Übersicht</a></li>
                                    </ul>
                                </li>
                            }
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav><!-- /navigation -->
        </header>
    </div>





    @*-----------------------------------------------------Scripts ---------------------------------------------*@

  
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "positionClass": "toast-top-right",
            "onclick": null,
            "showDuration": "400",
            "hideDuration": "1000",
            "timeOut": "3000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        $(document).ready(function () {

            @if (TempData["ErrorMessage"] != null)
            {
                <text>
            toastr.error("", "@TempData["ErrorMessage"]");
            </text>
            }

            @if (TempData["ConfirmMessage"] != null)
            {
                <text>
            toastr.success("", "@TempData["ConfirmMessage"]");
            </text>
            }

            });
    </script>
    <script>
        var myIndex = 0;
        carousel();

        function carousel() {
            var i;
            var x = document.getElementsByClassName("mySlides");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            myIndex++;
            if (myIndex > x.length) { myIndex = 1 }
            x[myIndex - 1].style.display = "block";
            setTimeout(carousel, 8000);
        }

    </script>
    <script>
        $(function () {
            $(".jqueryui-marker-datepicker").datepicker({
                dateFormat: "yy-mm-dd",
                changeYear: true,
                shownOn: "button"
            }).css("display", "inline-block")
            .next("button").button({
                icons: { primary: "ui-icon-calender" },
                label: "Bitte ein Datum aussuchen",
                text: false
            });
        });
    </script>
    <script>
    $('body').on('click','.option li',function(){
    var i = $(this).parents('.select').attr('id');
    var v = $(this).children().text();
    var o = $(this).attr('id');
    $('#'+i+' .selected').attr('id',o);
    $('#'+i+' .selected').text(v);
    });
    </script>

</body>
</html>

CardGame/CardGame.Web/Views/Shared/_Money.cshtml
@{
    ViewBag.Title = "_Money";
}

<div class="col col-md-12 currency">
    @{if (Session["CurrencyBalance"] != null)
            {
            <br style="height:0.5em"/>
            <h3>Dein Guthaben</h3>
           
            var currency = Session["CurrencyBalance"];
            <h5 class="welcome">@currency</h5>
            <h5 class="Welcome">COINS</h5>
            <img class="image responsive coinpic" src="~/Content/images/Coins-PNG-Picture-180x180.png" />
            <a class="btn btn-default" href="@Url.Action("EnableCurrency","CardPack")">Guthaben aufladen</a>  
             
        }
        else
        {
            <br style="height:0.5em"/>
            <h3>Lade dein Guthaben auf</h3>
            <img class="image responsive coinpic" src="~/Content/images/Coins-PNG-Picture-180x180.png" />
            <h3>und hol dir Cardpacks!!</h3>
        }
    }
</div>